import Anthropic from '@anthropic-ai/sdk';
import { CommitAnalysis, ProjectContext } from './types';

export class AICommitGenerator {
  private client: Anthropic;
  private model: string;

  constructor(apiKey: string, model: string = 'claude-3-5-sonnet-20241022') {
    this.client = new Anthropic({ apiKey });
    this.model = model;
  }

  async generateCommitMessage(
    diff: string,
    recentCommits: string[],
    projectContext: ProjectContext | null,
    readmeContent: string | null
  ): Promise<CommitAnalysis> {
    const systemPrompt = this.buildSystemPrompt(projectContext, readmeContent, recentCommits);
    const userPrompt = this.buildUserPrompt(diff);

    try {
      const message = await this.client.messages.create({
        model: this.model,
        max_tokens: 1024,
        system: systemPrompt,
        messages: [
          {
            role: 'user',
            content: userPrompt
          }
        ]
      });

      const responseText = message.content[0].type === 'text'
        ? message.content[0].text
        : '';

      return this.parseResponse(responseText, diff);
    } catch (error: any) {
      throw new Error(`AI generation failed: ${error.message}`);
    }
  }

  private buildSystemPrompt(
    projectContext: ProjectContext | null,
    readmeContent: string | null,
    recentCommits: string[]
  ): string {
    let prompt = `You are an expert at writing clear, concise git commit messages.

Your task is to analyze git diffs and generate a single-line commit message that:
- Is concise (50-72 characters ideal)
- Uses imperative mood (e.g., "Add feature" not "Added feature")
- Focuses on the "what" and "why", not the "how"
- Follows conventional commit patterns when appropriate (feat:, fix:, chore:, docs:, etc.)

`;

    if (recentCommits.length > 0) {
      prompt += `\nRecent commit messages from this repository for style reference:\n`;
      recentCommits.slice(0, 5).forEach(commit => {
        prompt += `- ${commit}\n`;
      });
    }

    if (projectContext?.commitStyle) {
      prompt += `\nThis project uses the following commit style: ${projectContext.commitStyle}\n`;
    }

    if (projectContext?.projectType) {
      prompt += `\nProject type: ${projectContext.projectType}\n`;
    }

    if (readmeContent) {
      const truncatedReadme = readmeContent.slice(0, 1000);
      prompt += `\nProject description (from README):\n${truncatedReadme}\n`;
    }

    prompt += `\nRespond with ONLY the commit message (one line). Do not include quotes, explanations, or additional text.`;

    return prompt;
  }

  private buildUserPrompt(diff: string): string {
    const maxDiffLength = 6000;
    let truncatedDiff = diff;

    if (diff.length > maxDiffLength) {
      truncatedDiff = diff.slice(0, maxDiffLength) + '\n\n... (diff truncated)';
    }

    return `Generate a commit message for these changes:\n\n${truncatedDiff}`;
  }

  private parseResponse(response: string, diff: string): CommitAnalysis {
    const message = response.trim();

    const lines = diff.split('\n');
    const insertions = lines.filter(l => l.startsWith('+')).length;
    const deletions = lines.filter(l => l.startsWith('-')).length;
    const filesChanged = (diff.match(/^diff --git/gm) || []).length;

    return {
      message,
      reasoning: 'Generated by AI analysis of git diff',
      filesChanged,
      insertions,
      deletions
    };
  }

  async analyzeProjectType(readmeContent: string, fileList: string[]): Promise<string> {
    try {
      const message = await this.client.messages.create({
        model: this.model,
        max_tokens: 256,
        messages: [
          {
            role: 'user',
            content: `Based on this README and file list, identify the project type in 2-3 words (e.g., "Node.js CLI tool", "React web app", "Python library", "WordPress theme"):\n\nREADME:\n${readmeContent.slice(0, 500)}\n\nFiles: ${fileList.slice(0, 20).join(', ')}\n\nRespond with ONLY the project type, nothing else.`
          }
        ]
      });

      const responseText = message.content[0].type === 'text'
        ? message.content[0].text
        : 'Unknown';

      return responseText.trim();
    } catch {
      return 'Unknown';
    }
  }
}
